import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import {gql, useQuery,NetworkStatus} from "@apollo/client";
import {Box, Button, Heading, SimpleGrid, Spinner} from "@chakra-ui/react"


let pageNumber = 1
const GET_PEOPLE = gql`
    query People($pageNumber:Float!) {
        people(page:$pageNumber) {
            name
        }
    }
`;

const Home: NextPage = () => {

    const { data, loading, error, refetch,networkStatus } = useQuery(GET_PEOPLE,{
        variables:{pageNumber:pageNumber},
        notifyOnNetworkStatusChange: true,
    });

    let handleNextClick = () => {
        if(pageNumber == 9) return;
        pageNumber +=1

        refetch({
            pageNumber:pageNumber
        })
        console.log(pageNumber);
    }

    let handlePreviousClick = () => {
        if(pageNumber == 1) return;

        pageNumber -=1

        refetch({
            pageNumber:pageNumber
        })
        console.log(pageNumber);
    }


    if (loading || networkStatus === NetworkStatus.refetch) {
        return (
            <div className={styles.container}>
                <Image src="/star-wars.svg" alt="Star Wars Logo" width={120} height={120} />
                <Spinner />
            </div>

        )
    }

    if (error) {
        console.error(error);
        return null;
    }

  return (
    <div className={styles.container}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
          <Image src="/star-wars.svg" alt="Star Wars Logo" width={120} height={120} />

              <SimpleGrid columns={2} spacing={10}>
              {data.people.map((person:any) =>(
                  <Box key={person.name} maxW="sm" p={6} borderWidth="1px" borderRadius="md" overflow="hidden">
                      <Heading mb="0" as="h4" size="md">{person.name}</Heading>
                  </Box>
              ))}
              </SimpleGrid>
            <br/>
          <Button onClick={handleNextClick}  colorScheme="black" variant="outline">
              Next Page
          </Button>
          <Button onClick={handlePreviousClick}  colorScheme="black" variant="outline">
              Previous Page
          </Button>
      </main>

    </div>
  )
}


export default Home
